import { StyleSheet } from "react-native";
import { theme } from "./theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.bg },
  container: { flex: 1, padding: 12, alignItems: "center", justifyContent: "center" },
  vignette: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  card: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1.5,
    borderColor: theme.line,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    width: "100%",
    maxWidth: 440,
    alignSelf: "center",
  },
  hero: { color: "#fefefe", fontSize: 26, fontWeight: "900", marginBottom: 6, textShadowColor: "rgba(0,0,0,0.35)", textShadowRadius: 6 },
  subhero: { color: theme.muted, fontSize: 13, marginBottom: 8, fontWeight: "700" },
  title: { color: theme.text, fontSize: 24, fontWeight: "800", marginBottom: 8 },
  label: { color: theme.muted, fontSize: 14, marginBottom: 6 },
  helper: { color: theme.muted, fontSize: 13, marginBottom: 10 },
  handoutShell: { width: "100%", maxWidth: 440, alignSelf: "center" },
  handoutCard: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    rowGap: 12,
  },
  poster: {
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
  },
  posterInner: {
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  posterTitle: { color: "#fff", fontSize: 20, fontWeight: "900", letterSpacing: 0.2 },
  posterSubtitle: { color: "rgba(255,255,255,0.8)", fontSize: 14, marginTop: 4 },
  posterEmoji: { fontSize: 36, marginRight: 8 },
  row: { flexDirection: "row", alignItems: "center", marginBottom: 8, gap: 8 },
  rowSpread: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginVertical: 12 },
  input: {
    flex: 1,
    backgroundColor: "#161925",
    color: theme.text,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.line,
    minHeight: 38,
  },
  delete: { color: theme.danger, fontSize: 16, paddingHorizontal: 8 },
  inputIcon: { color: theme.muted, marginLeft: 4, marginRight: 4 },
  secondaryButton: {
    borderColor: theme.accent,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 10,
    marginTop: 8,
  },
  secondaryText: { color: theme.accent, textAlign: "center", fontWeight: "600" },
  primaryButton: {
    backgroundColor: theme.accent,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: "center",
    marginTop: 10,
  },
  primaryText: { color: "#0b0c10", fontWeight: "800", fontSize: 15 },
  pill: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.line,
    marginRight: 6,
  },
  pillActive: { backgroundColor: theme.accent, borderColor: theme.accent },
  pillText: { color: theme.text },
  pillTextActive: { color: "#0b0c10", fontWeight: "700" },
  toggle: {
    width: 50,
    height: 28,
    borderRadius: 20,
    backgroundColor: theme.line,
    padding: 4,
    justifyContent: "center",
  },
  knob: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: theme.muted,
    alignSelf: "flex-start",
  },
  knobOn: { alignSelf: "flex-end", backgroundColor: theme.accent, shadowColor: theme.accent, shadowOpacity: 0.8, shadowRadius: 6, shadowOffset: { width: 0, height: 0 } },
  revealBox: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.line,
    marginVertical: 16,
  },
  impostorBox: { backgroundColor: "#2b0b0b", borderColor: "#7f1d1d" },
  civilBox: { backgroundColor: "#0b2b1f", borderColor: "#14532d" },
  revealTitle: { color: theme.text, fontSize: 20, fontWeight: "700", marginBottom: 6 },
  revealText: { color: theme.text, fontSize: 16, marginBottom: 4 },
  revealHint: { color: theme.muted, fontSize: 15 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginVertical: 12 },
  tile: {
    width: "30%",
    minWidth: 90,
    backgroundColor: "#161925",
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.line,
    alignItems: "center",
  },
  tileActive: { borderColor: theme.accent, backgroundColor: "#1f2433" },
  tileText: { color: theme.text, fontWeight: "600" },
  rowText: { color: theme.text, fontSize: 16, marginBottom: 6 },
});
